name: Random Tangent Side Note
favicon: null
layout_spectrum: 0.23234571609646082
typography_spectrum: 0.15938
title: 'RTSN: Random Tangent Side Notes From My Life'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-20126712-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3125
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
